
package org.itenas.oop.gevam.gems.tubes.view;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import org.itenas.oop.gevam.gems.tubes.config.ConnectionManager;
import org.itenas.oop.gevam.gems.tubes.model.Barang;
import org.itenas.oop.gevam.gems.tubes.model.Transaksi;
import org.itenas.oop.gevam.gems.tubes.repository.ControllerRiwayatTransaksi;
import java.sql.PreparedStatement;

/**
 *
 * @author arieb
 */


public class viewRiwayatTransaksi extends javax.swing.JFrame {
   
    Boolean hasil;
    Scanner sc = new Scanner(System.in);
    ConnectionManager conMan = new ConnectionManager();
    Connection con = conMan.logOn();
   

    public viewRiwayatTransaksi() {
        initComponents();
    }
    
    /**
     * Creates new form viewDashboardMenuKasir
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "ID Transaksi", "ID Barang", "Nama Barang", "Jumlah", "Harga Per-Item", "Total Harga"
            }
        ));
        tabelDetail.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelDetailAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelDetail);

        txtSearch.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtSearchAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDetailAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelDetailAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tabelDetail.getModel();
        dtm.setRowCount(0);
        String query = "SELECT d.id_detail, t.id_transaksi, b.id, b.namaBarang,d.jumlah, d.harga_peritem, d.totalHarga FROM detail_transaksi d"
                + " INNER JOIN transaksi t ON d.id_transaksi = t.id_transaksi INNER JOIN barang b"
                + " ON b.id = d.id";
        
        try (Statement stmt = con.createStatement(); 
                ResultSet rs = stmt.executeQuery(query)) {
            System.out.println("Daftar Transaksi:");
            while (rs.next()) {
                int idDetail = rs.getInt("id_detail");
                int idTransaksi = rs.getInt("id_transaksi");
                int Id = rs.getInt("id");
                String namaBarang = rs.getString("namaBarang");
                int Jumlah = rs.getInt("jumlah");
                double hargaPeritem = rs.getDouble("harga_peritem");
                double totalHarga = rs.getDouble("totalHarga");
               dtm.addRow(new Object[]{idDetail, idTransaksi, Id, namaBarang,Jumlah, hargaPeritem, totalHarga});
            }
           
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
        
    }//GEN-LAST:event_tabelDetailAncestorAdded

    private void txtSearchAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtSearchAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchAncestorAdded

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
   
    
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        btnSearch.addActionListener(e -> cariRiwayatTransaksiByNama());
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            cariRiwayatTransaksiByNama();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRiwayatTransaksi().setVisible(true);
            }
        });
    }
    
    private void cariRiwayatTransaksiByNama(){
        DefaultTableModel dtm = (DefaultTableModel) tabelDetail.getModel();
        dtm.setRowCount(0);
        String nama_barang = txtSearch.getText().trim();
        
       
        
        String query = "SELECT d.id_detail, t.id_transaksi, b.id, b.namaBarang,d.jumlah, d.harga_peritem, d.totalHarga FROM detail_transaksi d"
                + " INNER JOIN transaksi t ON d.id_transaksi = t.id_transaksi INNER JOIN barang b"
                + " ON b.id = d.id WHERE namaBarang LIKE ?";
        
        try {
                PreparedStatement dk = con.prepareStatement(query);
                dk.setString(1, "%" + nama_barang + "%");
                ResultSet rs = dk.executeQuery(); 
            System.out.println("Daftar Transaksi:");
            while (rs.next()) {
                int idDetail = rs.getInt("id_detail");
                int idTransaksi = rs.getInt("id_transaksi");
                int Id = rs.getInt("id");
                String namaBarang = rs.getString("namaBarang");
                int Jumlah = rs.getInt("jumlah");
                double hargaPeritem = rs.getDouble("harga_peritem");
                double totalHarga = rs.getDouble("totalHarga");
               dtm.addRow(new Object[]{idDetail, idTransaksi, Id, namaBarang,Jumlah, hargaPeritem, totalHarga});
            }
           
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDetail;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
